# coding: utf-8
# Contains 15 of IMDB's 250 most popular films of all time, as of 2016,
# from here: http://www.imdb.com/chart/top
IMDBData = {
    "Zootopia": {
        "Stars":["Ginnifer Goodwin", "Jason Bateman", "Idris Elba"],
        "Rating":8.1,
        "Genre":"Animation",
        "Year":2016,
        "URL Link":"http://www.imdb.com/title/tt2948356/",
    },
    "Martian": {
        "Stars":["Matt Damon", "Jessica Chastain", "Kristen Wiig"],
        "Rating":8.0,
        "Genre":"Sci-Fi",
        "Year":2015,
        "URL Link":"http://www.imdb.com/title/tt3659388",
    },
    "Hotel Rwanda": {
        "Stars":["Don Cheadle", "Sophie Okonedo", "Joaquin Phoenix"],
        "Rating":8.1,
        "Genre":"Drama",
        "Year":2004,
        "URL Link":"http://www.imdb.com/title/tt0395169",
    },
    "The Lord of the Rings: The Fellowship of the Ring": {
        "Stars":["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
        "Rating":8.8,
        "Genre":"Adventure",
        "Year":2001,
        "URL Link":"http://www.imdb.com/title/tt0120737",
    },
    "The Godfather": {
        "Stars":["Marlon Brando", "Al Pacino", "James Caan"],
        "Rating":9.2,
        "Genre":"Drama",
        "Year":1972,
        "URL Link":"http://www.imdb.com/title/tt0068646",
    },
    "Back to the Future": {
        "Stars":["Michael J. Fox", "Christopher Lloyd", "Lea Thompson"],
        "Rating":8.5,
        "Genre":"Sci-Fi",
        "Year":1985,
        "URL Link":"http://www.imdb.com/title/tt0088763",
    },
    "The Dark Knight": {
        "Stars":["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
        "Rating":9.0,
        "Genre":"Drama",
        "Year":2008,
        "URL Link":"http://www.imdb.com/title/tt0468569",
    },
    "A Beautiful Mind": {
        "Stars":["Russell Crowe", "Ed Harris", "Jennifer Connelly"],
        "Rating":8.2,
        "Genre":"Drama",
        "Year":2001,
        "URL Link":"http://www.imdb.com/title/tt0268978",
    },
    "Toy Story 3": {
        "Stars":["Tom Hanks", "Tim Allen", "Joan Cusack"],
        "Rating":8.3,
        "Genre":"Animation",
        "Year":2010,
        "URL Link":"http://www.imdb.com/title/tt0435761/",
    },
    "Forrest Gump": {
        "Stars":["Tom Hanks", "Robin Wright", "Gary Sinise"],
        "Rating":8.8,
        "Genre":"Drama",
        "Year":1994,
        "URL Link":"http://www.imdb.com/title/tt0109830",
    },
    "Inception": {
        "Stars":["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
        "Rating":8.8,
        "Genre":"Sci-Fi",
        "Year":2010,
        "URL Link":"http://www.imdb.com/title/tt1375666",
    },
    "The Matrix": {
        "Stars":["Keanu Reeves", "Laurence Fishburne", "Carie-Anne Moss"],
        "Rating":8.7,
        "Genre":"Sci-Fi",
        "Year":1999,
        "URL Link":"http://www.imdb.com/title/tt0133093",
    },
    "Saving Private Ryan": {
        "Stars":["Tom Hanks", "Matt Damon", "Tom Sizemore"],
        "Rating":8.6,
        "Genre":"Drama",
        "Year":1998,
        "URL Link":"http://www.imdb.com/title/tt0120815",
    },
    "Spirited Away": {
        "Stars":["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino"],
        "Rating":8.6,
        "Genre":"Animation",
        "Year":2001,
        "URL Link":"http://www.imdb.com/title/tt0245429",
    },
    "Captain America: Civil War": {
        "Stars":["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson"],
        "Rating":8.1,
        "Genre":"Sci-Fi",
        "Year":2016,
        "URL Link":"http://www.imdb.com/title/tt3498820",
    },
}
